using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace MDM.Models
{
    public partial class Country
    {
        public Country()
        {
            Address = new HashSet<Address>();
            State = new HashSet<Province>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Province> State { get; set; }
       
    }

    public partial class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {

            builder.Property(e => e.CreatedOn).HasColumnType("datetime");
            builder.Property(e => e.ModifiedOn).HasColumnType("datetime");
            builder.Property(e => e.Name).HasMaxLength(100);
        }

    }
    public static partial class Seeder
    {
        public static void SeedCountry(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country { Id = 1, Code = null, Name = "South Africa", Description = "South African", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 2, Code = null, Name = "Namibia", Description = "Namibian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 3, Code = null, Name = "Afghanistan", Description = "Afghan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 4, Code = null, Name = "Åland Islands", Description = "Åland Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 5, Code = null, Name = "Albania", Description = "Albanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 6, Code = null, Name = "Algeria", Description = "Algerian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 7, Code = null, Name = "American Samoa", Description = "American Samoa", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 8, Code = null, Name = "Andorra", Description = "Andorran", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 9, Code = null, Name = "Angola", Description = "Angolan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 10, Code = null, Name = "Anguilla", Description = "Anguilla", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 11, Code = null, Name = "Antarctica", Description = "Antarctica", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 12, Code = null, Name = "Antigua and Barbuda", Description = "Antigua and Barbuda", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 13, Code = null, Name = "Argentina", Description = "Argentinian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 14, Code = null, Name = "Armenia", Description = "Armenian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 15, Code = null, Name = "Aruba", Description = "Aruba", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 16, Code = null, Name = "Australia", Description = "Australian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 17, Code = null, Name = "Austria", Description = "Austrian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 18, Code = null, Name = "Azerbaijan", Description = "Azerbaijani", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 19, Code = null, Name = "Bahamas", Description = "Bahamian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 20, Code = null, Name = "Bahrain", Description = "Bahraini", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 21, Code = null, Name = "Bangladesh", Description = "Bangladeshi", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 22, Code = null, Name = "Barbados", Description = "Barbadian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 23, Code = null, Name = "Belarus", Description = "Belarusan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 24, Code = null, Name = "Belgium", Description = "Belgian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 25, Code = null, Name = "Belize", Description = "Belizean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 26, Code = null, Name = "Benin", Description = "Beninese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 27, Code = null, Name = "Bermuda", Description = "Bermuda", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 28, Code = null, Name = "Bhutan", Description = "Bhutanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 29, Code = null, Name = "Bolivia", Description = "Bolivian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 30, Code = null, Name = "Bonaire", Description = "Bonaire", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 31, Code = null, Name = "Bosnia-Herzegovina", Description = "Bosnian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 32, Code = null, Name = "Botswana", Description = "Botswanan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 33, Code = null, Name = "Bouvet Island", Description = "Bouvet Island", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 34, Code = null, Name = "Brazil", Description = "Brazilian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 35, Code = null, Name = "British Indian Ocean Territory", Description = "British Indian Ocean Territory", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 36, Code = null, Name = "Brunei", Description = "Bruneian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 37, Code = null, Name = "Bulgaria", Description = "Bulgarian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 38, Code = null, Name = "Burkina Faso", Description = "Burkinese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 39, Code = null, Name = "Burundi", Description = "Burundian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 40, Code = null, Name = "Cambodia", Description = "Cambodian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 41, Code = null, Name = "Cameroon", Description = "Cameroonian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 42, Code = null, Name = "Canada", Description = "Canadian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 43, Code = null, Name = "Cape Verde Islands", Description = "Cape Verdean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 44, Code = null, Name = "Cayman Islands", Description = "Cayman Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 45, Code = null, Name = "Central African Republic", Description = "Central African Republic", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 46, Code = null, Name = "Chad", Description = "Chadian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 47, Code = null, Name = "Chile", Description = "Chilean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 48, Code = null, Name = "China", Description = "Chinese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 49, Code = null, Name = "Christmas Island", Description = "Christmas Island", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 50, Code = null, Name = "Cocos (Keeling) Islands", Description = "Cocos (Keeling) Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 51, Code = null, Name = "Colombia", Description = "Colombian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 52, Code = null, Name = "Comoros", Description = "Comoros", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 53, Code = null, Name = "Congo", Description = "Congolese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 55, Code = null, Name = "Cook Islands", Description = "Cook Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 56, Code = null, Name = "Costa Rica", Description = "Costa Rican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 57, Code = null, Name = "Côte d'Ivoire", Description = "Côte d'Ivoire", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 58, Code = null, Name = "Croatia", Description = "Croatian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 59, Code = null, Name = "Cuba", Description = "Cuban", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 60, Code = null, Name = "Curaçao", Description = "Curaçao", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 61, Code = null, Name = "Cyprus", Description = "Cypriot", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 62, Code = null, Name = "Czech Republic", Description = "Czech", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 63, Code = null, Name = "Denmark", Description = "Danish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 64, Code = null, Name = "Djibouti", Description = "Djiboutian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 65, Code = null, Name = "Dominica", Description = "Dominican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 66, Code = null, Name = "Dominican Republic", Description = "Dominican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 67, Code = null, Name = "Ecuador", Description = "Ecuadorean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 68, Code = null, Name = "Egypt", Description = "Egyptian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 69, Code = null, Name = "Egypt", Description = "Egyptian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 70, Code = null, Name = "El Salvador", Description = "Salvadorean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 71, Code = null, Name = "Equatorial Guinea", Description = "Equatorial Guinea", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 72, Code = null, Name = "Eritrea", Description = "Eritrean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 73, Code = null, Name = "Estonia", Description = "Estonian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 74, Code = null, Name = "Eswatini", Description = "Eswatini", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 75, Code = null, Name = "Ethiopia", Description = "Ethiopian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 76, Code = null, Name = "Falkland Islands [Malvinas]", Description = "Falkland Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 77, Code = null, Name = "Faroe Islands", Description = "Faroe Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 78, Code = null, Name = "Fiji", Description = "Fijian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 79, Code = null, Name = "Finland", Description = "Finnish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 80, Code = null, Name = "France", Description = "French", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 81, Code = null, Name = "French Guiana", Description = "French Guiana", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 82, Code = null, Name = "French Polynesia", Description = "French Polynesia", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 83, Code = null, Name = "French Southern Territories", Description = "French Southern Territories", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 84, Code = null, Name = "Gabon", Description = "Gabonese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 85, Code = null, Name = "Gambia", Description = "Gambian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 86, Code = null, Name = "Georgia", Description = "Georgian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 87, Code = null, Name = "Germany", Description = "German", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 88, Code = null, Name = "Ghana", Description = "Ghanaian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 89, Code = null, Name = "Gibraltar", Description = "Gibraltar", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 90, Code = null, Name = "Greece", Description = "Greek", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 91, Code = null, Name = "Greenland", Description = "Greenland", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 92, Code = null, Name = "Grenada", Description = "Grenadian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 93, Code = null, Name = "Guadeloupe", Description = "Guadeloupe", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 94, Code = null, Name = "Guam", Description = "Guam", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 95, Code = null, Name = "Guatemala", Description = "Guatemalan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 96, Code = null, Name = "Guernsey", Description = "Guernsey", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 97, Code = null, Name = "Guinea", Description = "Guinean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 98, Code = null, Name = "Guinea-Bissau", Description = "Guinea-Bissau", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 99, Code = null, Name = "Guyana", Description = "Guyanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 100, Code = null, Name = "Haiti", Description = "Haitian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 101, Code = null, Name = "Heard Island and McDonald Islands", Description = "Heard Island and McDonald Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 102, Code = null, Name = "Holy See", Description = "Holy See", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 103, Code = null, Name = "Honduras", Description = "Honduran", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 104, Code = null, Name = "Hong Kong", Description = "Hong Kong", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 105, Code = null, Name = "Hungary", Description = "Hungarian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 106, Code = null, Name = "Iceland", Description = "Icelandic", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 107, Code = null, Name = "India", Description = "Indian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 108, Code = null, Name = "Indonesia", Description = "Indonesian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 109, Code = null, Name = "Iran", Description = "Iranian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 110, Code = null, Name = "Iraq", Description = "Iraqi", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 111, Code = null, Name = "Ireland", Description = "Irish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 112, Code = null, Name = "Isle of Man", Description = "Isle of Man", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 113, Code = null, Name = "Israel", Description = "Israel", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 114, Code = null, Name = "Italy", Description = "Italian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 115, Code = null, Name = "Jamaica", Description = "Jamaican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 116, Code = null, Name = "Japan", Description = "Japanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 117, Code = null, Name = "Jersey", Description = "Jersey", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 118, Code = null, Name = "Jordan", Description = "Jordanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 119, Code = null, Name = "Kazakhstan", Description = "Kazakh", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 120, Code = null, Name = "Kenya", Description = "Kenyan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 121, Code = null, Name = "Kiribati", Description = "Kiribati", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 122, Code = null, Name = "Kuwait", Description = "Kuwaiti", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 123, Code = null, Name = "Kyrgyzstan", Description = "Kyrgyzstan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 124, Code = null, Name = "Lao People's Democratic Republic", Description = "Lao People's Democratic Republic", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 125, Code = null, Name = "Laos", Description = "Laotian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 126, Code = null, Name = "Latvia", Description = "Latvian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 127, Code = null, Name = "Lebanon", Description = "Lebanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 128, Code = null, Name = "Lesotho", Description = "Lesotho", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 129, Code = null, Name = "Liberia", Description = "Liberian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 130, Code = null, Name = "Libya", Description = "Libyan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 131, Code = null, Name = "Liechtenstein", Description = "Liechtensteiner", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 132, Code = null, Name = "Lithuania", Description = "Lithuanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 133, Code = null, Name = "Luxembourg", Description = "Luxembourger", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 134, Code = null, Name = "Macao", Description = "Macao", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 135, Code = null, Name = "Macedonia", Description = "Macedonian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 136, Code = null, Name = "Madagascar", Description = "Madagascan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 137, Code = null, Name = "Malawi", Description = "Malawian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 138, Code = null, Name = "Malaysia", Description = "Malaysian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 139, Code = null, Name = "Maldives", Description = "Maldivian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 140, Code = null, Name = "Mali", Description = "Malian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 141, Code = null, Name = "Malta", Description = "Maltese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 142, Code = null, Name = "Marshall Islands", Description = "Marshall Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 143, Code = null, Name = "Martinique", Description = "Martinique", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 144, Code = null, Name = "Mauritania", Description = "Mauritanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 145, Code = null, Name = "Mauritius", Description = "Mauritian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 146, Code = null, Name = "Mayotte", Description = "Mayotte", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 147, Code = null, Name = "Mexico", Description = "Mexican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 148, Code = null, Name = "Micronesia", Description = "Micronesia", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 149, Code = null, Name = "Moldova", Description = "Moldovan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 150, Code = null, Name = "Monaco", Description = "Monacan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 151, Code = null, Name = "Mongolia", Description = "Mongolian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 152, Code = null, Name = "Montenegro", Description = "Montenegrin", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 153, Code = null, Name = "Montserrat", Description = "Montserrat", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 154, Code = null, Name = "Morocco", Description = "Moroccan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 155, Code = null, Name = "Mozambique", Description = "Mozambican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 156, Code = null, Name = "Myanmar", Description = "Burmese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 157, Code = null, Name = "Nauru", Description = "Nauru", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 158, Code = null, Name = "Nepal", Description = "Nepalese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 159, Code = null, Name = "Netherlands", Description = "Dutch", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 160, Code = null, Name = "New Caledonia", Description = "New Caledonia", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 161, Code = null, Name = "New Zealand", Description = "New Zealander", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 162, Code = null, Name = "Nicaragua", Description = "Nicaraguan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 163, Code = null, Name = "Niger", Description = "Nigerien", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 164, Code = null, Name = "Nigeria", Description = "Nigerian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 165, Code = null, Name = "Niue", Description = "Niue", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 166, Code = null, Name = "Norfolk Island", Description = "Norfolk Island", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 167, Code = null, Name = "North Korea", Description = "North Korean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 168, Code = null, Name = "Northern Mariana Islands", Description = "Northern Mariana Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 169, Code = null, Name = "Norway", Description = "Norwegian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 170, Code = null, Name = "Oman", Description = "Omani", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 171, Code = null, Name = "Pakistan", Description = "Pakistani", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 172, Code = null, Name = "Palau", Description = "Palau", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 173, Code = null, Name = "Palestine", Description = "Palestine", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 174, Code = null, Name = "Panama", Description = "Panamanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 175, Code = null, Name = "Papua New Guinea", Description = "Papua New Guinean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 176, Code = null, Name = "Paraguay", Description = "Paraguayan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 177, Code = null, Name = "Peru", Description = "Peruvian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 178, Code = null, Name = "Pitcairn", Description = "Pitcairn", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 179, Code = null, Name = "Poland", Description = "Polish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 180, Code = null, Name = "Portugal", Description = "Portuguese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 181, Code = null, Name = "Puerto Rico", Description = "Puerto Rico", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 182, Code = null, Name = "Qatar", Description = "Qatari", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 183, Code = null, Name = "Réunion", Description = "Réunion", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 184, Code = null, Name = "Romania", Description = "Romanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 185, Code = null, Name = "Russia", Description = "Russian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 186, Code = null, Name = "Rwanda", Description = "Rwandan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 187, Code = null, Name = "Saint Barthélemy", Description = "Saint Barthélemy", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 188, Code = null, Name = "Saint Helena", Description = "Saint Helena", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 189, Code = null, Name = "Saint Kitts and Nevis", Description = "Saint Kitts and Nevis", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 190, Code = null, Name = "Saint Lucia", Description = "Saint Lucia", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 191, Code = null, Name = "Saint Martin (French part)", Description = "Saint Martin (French part)", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 192, Code = null, Name = "Saint Pierre and Miquelon", Description = "Saint Pierre and Miquelon", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 193, Code = null, Name = "Saint Vincent and the Grenadines", Description = "Saint Vincent and the Grenadines", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 194, Code = null, Name = "Samoa", Description = "Samoa", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 195, Code = null, Name = "San Marino", Description = "San Marino", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 196, Code = null, Name = "Sao Tome and Principe", Description = "Sao Tome and Principe", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 197, Code = null, Name = "Saudi Arabia", Description = "Saudi Arabian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 198, Code = null, Name = "Scotland", Description = "Scottish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 199, Code = null, Name = "Senegal", Description = "Senegalese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 200, Code = null, Name = "Serbia", Description = "Serb or Serbian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 201, Code = null, Name = "Seychelles", Description = "Seychellois", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 202, Code = null, Name = "Sierra Leone", Description = "Sierra Leonian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 203, Code = null, Name = "Singapore", Description = "Singaporean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 204, Code = null, Name = "Sint Maarten (Dutch part)", Description = "Sint Maarten (Dutch part)", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 205, Code = null, Name = "Slovakia", Description = "Slovak", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 206, Code = null, Name = "Slovenia", Description = "Slovenian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 207, Code = null, Name = "Solomon Islands", Description = "Solomon Islander", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 208, Code = null, Name = "Somalia", Description = "Somali", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 209, Code = null, Name = "South Georgia and the South Sandwich Islands", Description = "South Georgia and the South Sandwich Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 210, Code = null, Name = "South Korea", Description = "South Korean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 211, Code = null, Name = "South Sudan", Description = "South Sudan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 212, Code = null, Name = "Spain", Description = "Spanish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 213, Code = null, Name = "Sri Lanka", Description = "Sri Lankan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 214, Code = null, Name = "Sudan", Description = "Sudanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 215, Code = null, Name = "Suriname", Description = "Surinamese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 216, Code = null, Name = "Svalbard and Jan Mayen", Description = "Svalbard and Jan Mayen", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 217, Code = null, Name = "SWAZILAND", Description = "Swazi", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 218, Code = null, Name = "Sweden", Description = "Swedish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 219, Code = null, Name = "Switzerland", Description = "Swiss", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 220, Code = null, Name = "Syria", Description = "Syrian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 221, Code = null, Name = "Taiwan", Description = "Taiwanese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 222, Code = null, Name = "Tajikistan", Description = "Tajik or Tadjik", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 223, Code = null, Name = "Tanzania", Description = "Tanzanian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 224, Code = null, Name = "Thailand", Description = "Thai", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 225, Code = null, Name = "Philippines", Description = "Philippine", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 226, Code = null, Name = "Timor-Leste", Description = "Timor-Leste", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 227, Code = null, Name = "Togo", Description = "Togolese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 228, Code = null, Name = "Tokelau", Description = "Tokelau", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 229, Code = null, Name = "Tonga", Description = "Tonga", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 230, Code = null, Name = "Trinidad and Tobago", Description = "Trinidadian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 231, Code = null, Name = "Tunisia", Description = "Tunisian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 232, Code = null, Name = "Turkey", Description = "Turkish", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 233, Code = null, Name = "Turkmenistan", Description = "Turkmen or Turkoman", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 234, Code = null, Name = "Turks and Caicos Islands", Description = "Turks and Caicos Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 235, Code = null, Name = "Tuvalu", Description = "Tuvaluan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 236, Code = null, Name = "Uganda", Description = "Ugandan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 237, Code = null, Name = "Ukraine", Description = "Ukrainian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 238, Code = null, Name = "United Arab Emirates", Description = "Emirati", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 239, Code = null, Name = "United Kingdom", Description = "Briton", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 240, Code = null, Name = "United States Minor Outlying Islands", Description = "United States Minor Outlying Islands", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 241, Code = null, Name = "United States of America", Description = "US citizen", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 242, Code = null, Name = "Uruguay", Description = "Uruguayan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 243, Code = null, Name = "Uzbekistan", Description = "Uzbek", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 244, Code = null, Name = "Vanuatu", Description = "Vanuatuan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 245, Code = null, Name = "Vatican City", Description = "Vatican", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 246, Code = null, Name = "Venezuela", Description = "Venezuelan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 247, Code = null, Name = "VietNam", Description = "Vietnamese", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 248, Code = null, Name = "Virgin Islands -U.S.", Description = "Virgin Islands -U.S.", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 249, Code = null, Name = "Virgin Islands-British", Description = "Virgin Islands-British", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 250, Code = null, Name = "Wales", Description = "Welsh", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 251, Code = null, Name = "Wallis and Futuna", Description = "Wallis and Futuna", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 252, Code = null, Name = "Western Sahara", Description = "Western Sahara", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 253, Code = null, Name = "Western Samoa", Description = "Western Samoan", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 254, Code = null, Name = "Yemen", Description = "Yemeni", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 255, Code = null, Name = "Yugoslavia", Description = "Yugoslav", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 256, Code = null, Name = "Zaire", Description = "Zaïrean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 257, Code = null, Name = "Zambia", Description = "Zambian", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) },
                new Country { Id = 258, Code = null, Name = "Zimbabwe", Description = "Zimbabwean", CreatedOn = new DateTime(2021, 2, 28), ModifiedOn = new DateTime(2021, 2, 28) }
                    );
        }
    }
}

